### PR TITLE
Create 2-tipping.md

### PR DESCRIPTION
**Pull request by maisieccino**
New episode. Still needs a longer description and audio file. also need to fix guid format

### CODE REVIEW

**Comment by maisieccino** [comment]
there's now an explicit GUID field on each episode which is separate from the episode URL

**Comment by abdulajet** [comment]
what is they benefit of the guid

**Comment by maisieccino** [comment]
> what is they benefit of the guid

you have to set one for the podcast feed, and once you set it you can't change it otherwise it's treated as a new episode. using an actual random string means I can change the URL/audio file name and it won't matter

**Review by abdulajet — APPROVED** [review]
LGTM

**Pull request merged**
